KVSlab/VaSP

postprocessing_fenics/compute_solid_stress.py
postprocessing_h5py/create_visualizations.py
postprocessing_h5py/postprocessing_common_h5py.py
preprocessing_mesh/PredeformFSIMesh.py

Fixed bug in create_domain_specific_viz.

Updated postprocessing_common_h5py

---

.gitignore
LICENSE

This PR adds license file and also update `.gitignore`

add License and update gitignore

---

environment.yml
pyproject.toml
src/fsipy/__init__.py
src/fsipy/automatedPreprocessing/__init__.py
src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py
src/fsipy/automatedPreprocessing/vmtkmeshgeneratorfsi.py

The new meshing script needs more work, so keeping the old meshing script for now.

Refactor and add vampy based meshing script

---

postprocessing_h5py/create_visualizations.py

Very small update, add overwrite toggle

Add overwrite toggle to create_visualizations.py

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py

This PR will allow user to choose number of sublayers in the fluid and solid domain from command line arguments. 
I modified parts of the scripts based on flake8.

add number of sublayer as command line arguments

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py

This PR includes:
- Added missing docs
- Added type hints to functions
- Fixing minor problem with xml mesh to hdf5 conversion

Add missing docs and add type hints to functions

---

.github/workflows/build_docs.yml

I forgot to include the deployment action in the last PR. With this fix, the webpage should show up.

added deployment action

---

src/fsipy/automatedPreprocessing/predeform_mesh.py

Related to https://github.com/KVSlab/turtleFSI/pull/81

change path to the mesh

---

pyproject.toml
src/fsipy/automatedPostprocessing/__init__.py
src/fsipy/automatedPostprocessing/postprocessing_mesh/__init__.py
src/fsipy/automatedPostprocessing/postprocessing_mesh/create_refined_mesh.py
src/fsipy/automatedPostprocessing/postprocessing_mesh/postprocessing_mesh_common.py

This is work-in-progress and just an example of how we can modify post-process scripts. 
We can look through this together during the meeting. @dbruneau-mie

Update post-process: 1st step - worked on creating refined mesh with the correct ID markers and ordered nodal coordinate

---

postprocessing_h5py/create_spectrogram_from_components.py
postprocessing_h5py/create_spectrograms_chromagrams.py
postprocessing_h5py/determine_modal_frequencies.py
postprocessing_h5py/postprocessing_common_h5py.py
postprocessing_h5py/spectrograms.py

Added option to take spectrogram for specific solid region given by "domains" in a specified mesh.

Add domain-based spectrogram sampling

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py
tests/test_pre_processing.py

Implementation of #45 as a part of pre-processing. 
Also, I found one unused parameter `add_boundary_layer’ and removed it.

Add edge length evaluator

---

README.md

Although not complete, I updated `README` for the repository.

very first update of readme

---

pyproject.toml
src/fsipy/automatedPostprocessing/log_plotter.py

This Python script provides a flexible solution for parsing and visualizing simulation log files created by `turtleFSI`. It enables users to extract data from log files, offers flexible plotting options, and helps in gaining insights from simulation results.
Usage Example:
``` shell
fsipy-log-plotter simulation.log --plot-all --save --output-directory Results --figure-size 12,8
```
Functions:
* `parse_log_file`: Parses a log file and stores data in a structured dictionary with NumPy arrays.
* `parse_dictionary_from_log`: Parses a dictionary-like content from a log file and returns it as a dictionary.
* `plot_variable_vs_time`: Plots a variable against time with optional saving of the figure.
* `plot_variable_comparison`: Plots a comparison of a variable across multiple cycles.
* …

Add log file parsing and plotting script

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/simulations/simulation_common.py

Switch to json when generating/loading probe points

fix generating/loading probe points

---

postprocessing_fenics/compute_readable_h5.py
postprocessing_h5py/compute_spi.py
postprocessing_h5py/create_harmonic_concentration_index.py
postprocessing_h5py/determine_modal_frequencies_one_time.py
postprocessing_h5py/overlay_modes_on_spectrograms.py
postprocessing_h5py/postprocessing_common_h5py.py
postprocessing_h5py/postprocessing_common_pv.py
postprocessing_h5py/subtract_spectrograms.py
postprocessing_h5py/wss_region.py

Edits to postprocessing_fenics and postprocessing_h5py, mostly adding functionality for modal analysis

Edits to folders that will eventually be deleted/merged into src

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py
tests/test_pre_processing.py

This PR refactors the pre-processing tests and adds testing of command line options for `fsipy-mesh` script.

Refactor pre-processing tests

---

src/fsipy/simulations/offset_stenosis.py

This PR improves offset stenosis problem file. Now it includes functionality from `simulation_common.py`for printing CFL, Reynolds number, velocity/pressure from probes.

improve offset stenosis problem file

---

src/fsipy/simulations/aneurysm.py

Hey Kei, here is the un-tested aneurysm simulation file. Attatching the aneurysm mesh file here as a .txt file, need to change the extension to .h5 to use it.
[file_aneurysm.txt](https://github.com/KVSlab/Aneurysm_Workflow_FSI/files/12932577/file_aneurysm.txt)
For permanent storage/linking these mesh files, should we upload the meshes as separate entries in Zenodo, or upload all of them in a single folder on Zenodo?

Add aneurysm simulation file

---

.github/workflows/build_docs.yml
docs/_toc.yml
docs/api.rst

Adds python API in the documentation. Right now, it only contains pre-processing part, but we can add more easily anytime.

Add python api

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py
tests/test_simulation_common.py

Some improvements to meshing:
* Added option `--no-solid` to generate a mesh without the solid.
* Incremented the inlet and outlet ID's by 1 in the `_info.json` file such that it can be used in the problem files.

Meshing improvements

---

src/fsipy/automatedPostprocessing/postprocessing_fenics/create_hdf5.py

Just minor improvement of `create_hdf5.py`. When dealing with HDF5, it is much faster to take all the data and slice it after that.

minor improvement of create_hdf5

---

src/fsipy/simulations/avf.py

add first version of avf problem file. Major difference from aneurysm and stenosis is that 
1. Two solid regions
2. Parabolic inflow profile instead of Womersley flow

add avf problem file

---

pyproject.toml
src/fsipy/automatedPostprocessing/postprocessing_fenics/create_hdf5.py
src/fsipy/automatedPostprocessing/postprocessing_fenics/create_separate_domain_visualization.py

This PR adds functionality to get separate domain visualization for the velocity on fluid domain and displacement on either solid or entire domain. The outputted visualization depends on how you run `create_hdf5.py` prior to running this new script called `create_separate_domain_visualization.py`. 
Please see the following image as an example of displacement on solid domain only and velocity on fluid domain.

add separate domain visualization script

---

src/fsipy/automatedPostprocessing/postprocessing_h5py/create_spectrograms_chromagrams.py
src/fsipy/automatedPostprocessing/postprocessing_h5py/create_spectrum.py
src/fsipy/automatedPostprocessing/postprocessing_h5py/postprocessing_common_h5py.py
src/fsipy/automatedPostprocessing/postprocessing_h5py/spectrograms.py

This pull request addresses two issues in the spectrogram code:
1. Fixes an issue with the transformed matrix filename (removed `case_name`).
2. Resolves a circular import issue by moving the `sonify_point` function to `spectrograms.py`.

Fixes in spectrogram code

---

src/fsipy/automatedPostprocessing/postprocessing_fenics/create_hdf5.py
src/fsipy/automatedPostprocessing/postprocessing_fenics/create_separate_domain_visualization.py

This PR moves function for reading command line argument from common file to each files. In addition, I added `tqdm` for `create_hdf5` script. I will remove `parse_arguments` from `postprocessing_fenics_common.py` after #111 is merged to avoid potential conflict between PRs.

Move argparser

---

src/fsipy/simulations/cylinder.py
tests/test_simulations.py

add pytest for cylinder problem.

Add test cylinder

---

pyproject.toml
src/fsipy/automatedPreprocessing/__init__.py
src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py
src/fsipy/automatedPreprocessing/vmtkmeshgeneratorfsi.py
src/fsipy/simulations/simulation_common.py
tests/test_pre_processing.py
tests/test_simulation_common.py

Pull request summary:
* Renames the mesh generation script from `fsipy-mesh` to `fsipy-generate-mesh` for consistency.
* Introduces a new option `--extract-branch` to the meshing script for marking solid mesh IDs with an offset for a specific branch.
* Adds options `--branch-group-ids` to specify group IDs for extraction and `--branch-ids-offset` to control the offset (default 1000).
* The offset parameter is added to the parameters file.
* Adds missing copyright headers to the preprocessing scripts.

Preprocessing improvements

---

src/fsipy/automatedPostprocessing/postprocessing_h5py/postprocessing_common_h5py.py

very minor fix due to changes in the naming of strain. I will merge without review

fix strain name

---

.dockerignore
.github/workflows/docker.yml
docker/Dockerfile

add docker related files

---

script_params.config

will merge without review because it’s just removing unused file

remove unused config file

---

src/fsipy/automatedPostprocessing/postprocessing_h5py/spectrograms.py
src/fsipy/simulations/offset_stenosis.py
src/fsipy/simulations/offset_stenosis_box.py

This PR adds two things
1. offset stenosis problem where FSI region is defined with a box instead of sphere
2. a way of creating spectrogram with a box instead of sphere

Add a way creating spectrogram with a box

---

src/vasp/automatedPostprocessing/postprocessing_fenics/compute_stress_strain.py

compute time-average of max principal stress & strain

compute average of max principal stress & strain

---

src/vasp/automatedPostprocessing/postprocessing_h5py/create_hi_pass_viz.py

minor bug fix for the high pass visualization script. Percentile plot was not correct, but should be fixed with this.

minor bug fix in high-pass visualization

---

src/vasp/automatedPostprocessing/postprocessing_h5py/create_hi_pass_viz.py
src/vasp/automatedPostprocessing/postprocessing_h5py/postprocessing_common_h5py.py

found a bug in the new high pass strain implementation. The problem mostly comes from the fact that we are using DG element for strain now and `write_checkpoint` for saving the file.

Fix high pass strain

---

environment.yml

Downgrade expat to fix problem with XML parsing

---

src/vasp/automatedPreprocessing/automated_preprocessing.py

This pull request adds the ability to run the `distancetospheres` meshing method multiple times with distinct parameters for each run.

Allow multiple runs of 'distancetospheres' method

---

src/vasp/automatedPostprocessing/postprocessing_h5py/create_hi_pass_viz.py

Minor update of `create_hi_pass_viz.py`
1. In case of strain, we have one extra output file for high-pass filtered maximum principal strain. With `--overwrite` flag, vasp now makes sure that the extra file is also deleted. 
2. With high-pass filtered pressure, wrong array was assigned as `rms_magnitude`. As a result, auto-generated plot is now correct. (h5 file was already correct)
3. By default, vasp used to check if strain is computed on the solid or entire domain regardless of the output you want to filter. Now vasp only checks it if the variable is strain.

minor update of create_hi_pass_viz.py

---

src/vasp/automatedPostprocessing/postprocessing_fenics/create_hdf5.py
tests/test_create_hdf5.py

add pytest for creating FEniCS compatible HDF5 files for the velocity and displacement after running FSI simulation.

add pytest for `create_hdf5.py`

---

src/vasp/automatedPreprocessing/automated_preprocessing.py

This pull request addresses a variable name conflict in the code related to meshing parameters.

Fix variable name conflict in meshing parameters loop

---

.github/workflows/check_and_test_package.yml

fix issue with CI

---

src/vasp/automatedPostprocessing/postprocessing_fenics/compute_hemodynamics.py
tests/test_compute_hemodynamics.py

Fix #157 and improved pytest to make sure that OSI value is between 0 and 0.5.

Fix issue with hemodynamic indices computation

---

.github/workflows/check_and_test_package.yml
src/vasp/automatedPostprocessing/postprocessing_h5py/create_spectrograms_chromagrams.py
src/vasp/automatedPostprocessing/postprocessing_h5py/spectrograms.py

found a minor bug when selecting `--interface-only` option and is fixed. Also modified the `save_deg` parameter so that is is automatically set to 1 when selecting pressure.

fix problem with interface_only option

---

src/vasp/simulations/aneurysm.py

* compute time averaged displacement/velocity/pressure during the simulation and save it in the `Visualization` folder.
* Use `save_solution_after_tstep` to specify when to start sampling the data.

add time-averaged values

---

src/vasp/automatedPreprocessing/automated_preprocessing.py
src/vasp/simulations/offset_stenosis.py
src/vasp/simulations/offset_stenosis_box.py
src/vasp/simulations/simulation_common.py
tests/test_simulation_common.py

use vampy for printing mesh info

---

docs/docker.md

add more detailed instructions on how to use docker.

enrich docker documentation

---

.github/workflows/check_and_test_package.yml

#180 resulted in failure of CI. This PR should fix the issue.

fix problem with mamba in CI

---

.github/workflows/build_docs.yml
.github/workflows/check_and_test_package.yml

ref: https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/

use miniforge instead of mambaforge in CI

---

src/vasp/automatedPostprocessing/postprocessing_h5py/create_hi_pass_viz.py

A very minor fix of high-pass visualization script. Will merge without a review.

use consistent array name for the pressure in high-pass viz

---

README.md
docs/_config.yml
docs/index.md
docs/simulation.md

This PR includes update of the landing page of documentation to include brief summary of vasp. Also, some very minor updates of documentation (fixing typo, etc).

Update  landing page of the documentation

---

LICENSE
src/vasp/__init__.py
src/vasp/automatedPostprocessing/postprocessing_h5py/__init__.py
src/vasp/automatedPostprocessing/predeform_mesh.py
src/vasp/automatedPreprocessing/generate_solid_probe.py
src/vasp/simulations/__init__.py
src/vasp/simulations/aneurysm.py
src/vasp/simulations/avf.py
src/vasp/simulations/cylinder.py
src/vasp/simulations/predeform.py

add missing license to all the files in the repository. Additionally, I modified LICENSE file to contain any relevant license, per discussion with @johannesring

Address license

---

src/vasp/postprocessing/postprocessing_h5py/create_hi_pass_viz.py
src/vasp/postprocessing/postprocessing_h5py/postprocessing_h5py_common.py

This PR includes a few updates on the filtering visualization functions. Previous implementation determined timestep based on parameters used for the FSI simulation. However, some post-processing is performed with stride. This update fixes this mismatch. Additionally, filtering of the stress is now included.

updates on filtering visualization function

---

src/vasp/postprocessing/postprocessing_h5py/create_hi_pass_viz.py

Fix https://github.com/KVSlab/VaSP/pull/225#discussion_r2094956031

fix minor bug in high pass viz
