KVSlab/VaSP

postprocessing_h5py/check_h5file.py
postprocessing_h5py/combine_xdmf.py

Hi @dbruneau-mie 
This PR adds two scripts that can be used to fix h5/xdmf files with inconsistent mesh information. 
When restarting turtleFSI, h5 files can contain mesh/vector information with different ordering due to different mesh partitioning and `check_h5file.py` can be used to correct the mesh/vector ordering based on one of the h5 files. 
After fixing, one can use `combine_xdmf.py’ to safely merge xdmf files. This also means that it is better not to merge visualization files at the end of the simulation, but we can come back to this in the turtle meeting.
Please let me know if you have any questions!
Best,
Kei

add scripts to fix (spatial) restart problem

---

preprocessing_mesh/predeform_mesh.py

I updated the script to perform pre-deformation of the mesh. The main difference from the previous version is that 
1. You only need to parse the path to the folder. The script will get the last time step without giving parameter for time step.
2. It is assumed that the `mesh.h5` is saved inside `Checkpoint` folder. `turtleFSI` or problem files need to be modified but I think it makes post-processing easier if we save mesh inside the resulting folder. Happy to take any opinion on this.

rename and update predeformation script

---

pyproject.toml
src/fsipy/__init__.py
src/fsipy/automatedPreprocessing/__init__.py
src/fsipy/automatedPreprocessing/predeform_mesh.py

I have made some changes to the predeform mesh script:
* The script is now installed as `fsipy-predeform-mesh` when running `pip install`.
* Added `--help` option.
* Added a new optional command-line argument `--mesh-path` with a default value of `<folder_path>/Checkpoint/mesh.h5` to specify the path to the mesh file.
* Switched to use the `pathlib` library.
* Added docstrings and type hints to functions.
* Added print statements to provide informative feedback about the progress of the script and the result of the mesh predeformation.

Mesh predeformation enhancements

---

environment.yml
src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py
tests/test_pre_processing.py

In this pull request a new function `convert_vtu_mesh_to_xdmf` has been added, enabling the conversion of VTU mesh data to the XDMF format using the `meshio` library. Currently, the mesh is converted from VTU to XML and from XML to HDF5. With the change in this PR, the mesh is converted directly from VTU to XDMF. The resulting XDMF mesh can be used in the same way as in [Stenosis_2D.py](https://github.com/KVSlab/turtleFSI/blob/34925bed03008e463ce6ddc82b875287fc866177/turtleFSI/problems/Stenosis_2D.py#L69-L91) in turtleFSI. One thing that is good about using XDMF is that the mesh can easily be viewed in ParaView. Do we want to keep using HDF5 or should we switch to XDMF? Please let me know your thoughts.

Add VTU to XDMF mesh conversion using meshio

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py

This change adds a `compute_flow_rate` function and a `--flow-rate-factor` option to `fsipy-mesh`. The default value is `0.31`. The function is copied more or less from VaMPy and maybe this change should be added in VaMPy instead.

Add --flow-rate-factor option

---

src/fsipy/__init__.py
src/fsipy/simulations/__init__.py
src/fsipy/simulations/simulation_common.py

In this pull request I have added a set of functions in a new file called `simulation_common.py`. These functions provides various functionalities for mesh and data handling, as well as some flow analysis. Here's a short summary of each function:
* `load_mesh_and_data`: Loads mesh, boundary data, and domain data from an HDF5 file.
* `print_mesh_summary`: Prints geometric information about a volumetric mesh.
* `load_mesh_info`: Loads and processes mesh information from a JSON file, returning various parameters like inlet IDs, outlet IDs, wall ID, mean flow rate, area ratios, and inlet areas. The information in the JSON file is currently not always correct, so this function is not so useful yet.
* `load_probe_points`: Loads probe points from a file based on the mesh file's path.
* …

Add common simulation functions

---

.github/workflows/check_and_test_package.yml

This PR adds code coverage report monitoring with codecov. I had to add `--editable` when installing fsipy so that pytest covers `src` folder. Otherwise, it will only report the coverage of the test itself.

add coverage report with codecov

---

tests/test_simulation_common.py

In this pull request I have added a new file `test_simulation_common.py`, containing the following:
* `temporary_hdf5_file`: Fixture for generating a temporary HDF5 file path with a mesh for testing purposes.
* `test_load_mesh_and_data`: Tests the `load_mesh_and_data` function for loading mesh and data from an HDF5 file.
* `test_load_mesh_info`: Tests the `load_mesh_info` function with specific expected values.
* `test_print_mesh_summary`: Tests the `print_mesh_summary` function by capturing and checking its printed output.
* `test_load_probe_points`: Tests the `load_probe_points` function by comparing loaded probe points with expected values.
Suggestions for improvements or other ways to test the functions are welcome.

Add some tests for common simulation functions

---

src/fsipy/simulations/simulation_common.py

Add fluid density parameter for accurate Reynolds number calculation.

Add fluid density parameter for Reynolds number calculation

---

postprocessing_h5py/postprocessing_common_h5py.py
postprocessing_h5py/spectrograms.py
src/fsipy/simulations/cylinder.py

Simple test cylinder added to repo.

Add simple test cylinder

---

tests/test_pre_processing.py

Refactor test paths to use a temporary directory for pre-processing tests. This change ensures that tests run in isolation without affecting the original data. Fixes issue #57.

Refactor pre-processing test paths to use a temporary directory

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py

This change includes the parameters file (`_info.json`) in the `--remove-all` option, ensuring that it is removed when cleaning up files.

Make sure parameters file is removed when using --remove-all

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py
src/fsipy/automatedPreprocessing/vmtkmeshgeneratorfsi.py
src/fsipy/simulations/simulation_common.py
tests/test_simulation_common.py

This change adds new command line arguments to `fsipy-mesh`, specifically `--solid-side-wall-id`, `--interface-fsi-id`, `--interface-outer-id`, `--volume-id-fluid`, and `--volume-id-solid`. It also adds the functionality to write these ID values to the parameters file (`_info.json`). The `generate_mesh` function in `preprocessing_common.py` now also accepts these ID values as arguments. The change also includes modifications to the `load_mesh_info` function in `simulation_common.py` to return a named tuple `MeshInfo` containing all relevant mesh information, including the new ID values. The test functions have also been updated to reflect these changes.

Include mesh IDs in parameter file

---

src/fsipy/__init__.py
src/fsipy/automatedPostprocessing/__init__.py
src/fsipy/automatedPreprocessing/__init__.py
src/fsipy/simulations/__init__.py

The goal of this pull request is to prevent the unnecessary import of all submodules when importing a specific submodule (should fix issue #69).

Restructure package imports to avoid import of unnecessary submodules

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py

This test for re-meshing was not useful, so removed. In many cases this only made the mesh generation run twice, but the resulting mesh was the same as before re-meshing.

Remove unuseful re-meshing test

---

src/fsipy/automatedPostprocessing/postprocessing_mesh/create_refined_mesh.py

there were two for loops that were easy to vectorize inside `create_refined_mesh.py`

remove redundant for loops 

---

src/fsipy/automatedPostprocessing/postprocessing_mesh/separate_mesh.py

This pull request updates the code in `separate_mesh.py` to load data from a JSON file (`default_variables.json`) instead of a pickled file (`default_variables.pickle`). This to reflect the change in `turtleFSI`.

Replace pickle with json for loading default variables

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py
src/fsipy/automatedPreprocessing/vmtkmeshgeneratorfsi.py
tests/test_simulation_common.py

We had scaling from mm to m as a default when converting from xml to HDF5 while probes and other information inside `_info.json` file were not scaled. This PR changes default scaling to 1 (no scaling) and that the user should scale the input surface at the beginning of meshing so that probes are generated with scaled surface.

Refactor scaling

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py

In #77, I forgot to remove scaling of `solid_thickness_parameters` and it should be removed as there’s correct scaling happening later in the code 
https://github.com/KVSlab/Aneurysm_Workflow_FSI/blob/e5faff2870d02eb580ee73d36f371258b3f4cf99/src/fsipy/automatedPreprocessing/automated_preprocessing.py#L398-L400

remove solid thickness paramter sclaing duplicate

---

src/fsipy/automatedPostprocessing/log_plotter.py

This pull request improves the existing Python script for parsing and visualizing data from log files. The key changes include the addition of new functions and options related to Turbulent Kinetic Energy (TKE) calculations for probe points:
* Function `compute_tke`: Computes mean velocity, fluctuating velocity, and TKE for each point within a specified cycle range based on probe point data.
* Function `plot_probe_points_tke`: Plots TKE for each probe point in separate subplots.
* Function `plot_probe_points_tke_comparison`: Plots TKE per cycle for selected probe points in separate figures.
* Added `--plot-probe-points-tke` option to enable plotting of TKE for probe points. This can be used in combination with either `--compare-cycles` or ` --compute-average`.

Add TKE visualization for probe plots

---

src/fsipy/automatedPreprocessing/preprocessing_common.py

I found some typo related to the number of sublayers for fluid and solid. It will fail the test due to `VaMPy` update, but I think it is safe to just merge this.

fix solid and fluid sublayer typo

---

src/fsipy/automatedPreprocessing/automated_preprocessing.py
src/fsipy/automatedPreprocessing/preprocessing_common.py
src/fsipy/automatedPreprocessing/vmtkmeshgeneratorfsi.py

This PR adds an option `--mesh-generation-retries` to control how many mesh generation retries to run on TetGen failures.

Retry mesh generation on TetGen failures

---

src/fsipy/simulations/aneurysm.py
src/fsipy/simulations/cylinder.py
src/fsipy/simulations/predeform.py

I have added a simulation to pre-deform meshes. IT is similar to the "cylinder.py" simulation but has options to shift the start and end time of the pressure and velocity ramp. Also, the cylinder.py wouldn't run because it was missing a couple improts, that is also fixed in this PR

 Add pre-deform simulation (and fix cylinder.py)

---

src/vasp/automatedPreprocessing/automated_preprocessing.py
src/vasp/automatedPreprocessing/preprocessing_common.py

This PR includes the following meshing scripts improvements:
* Use `configargparse` to allow to generate a mesh using a config file (use the `--config` option in `vasp-generate-mesh`).
* Use `pathlib` for paths.
* Increase the number of default retries for mesh generation failures (trying to reduce failures on github).

Meshing script improvements

---

src/vasp/automatedPostprocessing/postprocessing_h5py/create_hi_pass_viz.py
src/vasp/automatedPostprocessing/postprocessing_h5py/postprocessing_common_h5py.py

We previously switched from using `write` to `write_checkpoint` when saving DG function values (strain/stress, WSS and so on). I noticed that h5 file generated with `write_checkpoint` saves mesh information for all the time steps even though the mesh is static. With this update, we will only save mesh information at the first time step when creating high pass filtered strain, which reduces file size significantly. 
Additionally, I also switched to using `libver=latest` when opening/creating h5 file. This seeps up the saving of arrays. 
https://docs.h5py.org/en/stable/high/file.html#version-bounding

Reduce file size

---

tests/test_postprocess_mesh.py

This PR adds pytest for two post-processing scripts relate to mesh; `vasp-refine-mesh`  and `vasp-separate-mesh`.

add pytest for post-process mesh script

---

src/vasp/automatedPostprocessing/postprocessing_fenics/create_hdf5.py

Following the discussion in #145, this PR changes the default setting of `vasp-create-hdf5` command. By default, it will extract the displacement from the solid domain only and the user should use `--extract-entire-domain` if they want to get the displacement from the entire domain.

make extract solid only as default

---

src/vasp/automatedPreprocessing/automated_preprocessing.py
src/vasp/automatedPreprocessing/preprocessing_common.py

Added the ability to switch between `euclidean` and `geodesic` distance computation methods in the preprocessing pipeline. Currently, this will only have effect when using the `distancetospheres` meshing method.
Here is an example of the difference between the two methods:
* `geodesic`
* `euclidean`

Add option to switch between 'euclidean' and 'geodesic' distance methods

---

src/vasp/automatedPostprocessing/postprocessing_h5py/create_hi_pass_viz.py

When filtering, we have an option to compute amplitude or not. It does not really make sense to compute amplitude when low-pass filtering displacement, velocity, or pressure, but is useful for low-pass filtered strain because we want to see the maximum principal component. Therefore, adding this if statement and skip window RMS, which is specific for high-pass filtered signal.

Not apply windowed rms when low-pass filtering

---

src/vasp/automatedPostprocessing/postprocessing_h5py/create_spectrograms_chromagrams.py
src/vasp/automatedPostprocessing/postprocessing_h5py/spectrograms.py

Add PointList sampling for spectrograms
This allows us to make multi-point sonifications from list of points
Add "all" option for spectrogram components, superceding the need for "create_spectrogram_from_components.py"
This also allows us to make sonifications including all components

Add PointList sampling for spectrogram, superceding SinglePoint sampling

---

src/vasp/automatedPostprocessing/postprocessing_h5py/create_spectrograms_chromagrams.py

minor fix for PSD and spectrogram plot.
Previously we modified `plt.ylim` based on the given `ylim` (frequency). However, PSD plot has frequency as x-axis and not y-axis. Therefore, changing the `xlim`.
The other change is just for the consistency for the spectrogram. y axis is labeled as Frequency [Hz], so I changed the x-axis from () to [] as well.

fix axis of figure

---

src/vasp/automatedPostprocessing/log_plotter.py
src/vasp/automatedPostprocessing/postprocessing_h5py/create_spectrograms_chromagrams.py

This pull request addresses several issues reported by mypy by adding necessary type assertions and casts. Fixes issue #167.

Add type assertions and casts to fix mypy issues

---

src/vasp/automatedPreprocessing/check_flatten_in_out.py

Added new script "check_flatten_in_out.py", which takes a .h5 mesh file and checks whether inlets and outlets are flat, then flattens them if they fall below a certain tolerance

Add functionality to check mesh inlets and outlets and flatten if necessary

---

src/vasp/automatedPreprocessing/automated_preprocessing.py
src/vasp/automatedPreprocessing/preprocessing_common.py

This PR adds functionality to create a mesh with painted surface mesh. Originally developed by @dbruneau-mie in the previous meshing framework and I integrated into the current meshing script.
To use this functionality, users need to have a painted surface mesh with thickness information in it and also need to install `pyvista`.

integrate meshing with painted surface into the main meshing script

---

src/vasp/automatedPreprocessing/automated_preprocessing.py

This PR introduces a feature to save command-line arguments to a file. 
This should ensure the reproducibility of the mesh.

modify meshing script to save given meshing command

---

.github/workflows/build_docs.yml
src/vasp/simulations/simulation_common.py
tests/test_simulations.py

This PR addresses two points in the current CFL number computation.
1. The minimum cell diameter was computed from rank 0 only in the previous implementation. By using `MPI.min`, we now get the minimum cell diameter from all the ranks. Technically, we should use the local cell diameter to compute CFL number,  but we stay in the safe range by using the minimum cell diameter and also is computationally efficient.
2. The current implementation does not take velocity degree in account. Although I couldn’t find a formal definition of CFL number with higher order elements, there are some papers addressing order dependency of the CFL number, such as [this one](https://www.math.uwaterloo.ca/~lgk/A_Characteristic_Based_CFL_Number.pdf). Might not be mathematically perfect way of computing CFL, but …

Fix computation of CFL number

---

src/vasp/automatedPreprocessing/automated_preprocessing.py
src/vasp/automatedPreprocessing/preprocessing_common.py
tests/test_pre_processing.py

This PR (fixing issue #197) introduces functionality to map thickness values to mesh points and adjust cell entity IDs based on the mapped thickness. The new capabilities include:
* Thickness mapping: A `map_thickness_to_mesh` function to assign thickness values from a surface to mesh points.
* Entity ID updates: An `update_entity_ids_by_thickness` function to adjust cell entity IDs based on average point thickness within defined ranges.
* Command-line support: Added a `--thickness-to-entity-id-mapping` argument to define thickness-to-ID mappings directly via the command line.
This works when using both `variable` and `painted` thickness for the solid.

Add support for thickness-based entity ID mapping in preprocessing

---

src/vasp/automatedPostprocessing/postprocessing_h5py/create_spectrograms_chromagrams.py
src/vasp/automatedPostprocessing/postprocessing_h5py/create_spectrum.py
src/vasp/automatedPostprocessing/postprocessing_h5py/spectrograms.py

This PR updates several default parameters for generating spectrograms. Also, I added `fsi_region` as a command-line argument, so that user flexibly modify its value. Finally, I added a check to see if specified `fsi_region` actually contains any nodes in it.

Minor update of spectrogram default parameters

---

src/vasp/automatedPostprocessing/log_plotter.py
src/vasp/simulations/aneurysm.py
src/vasp/simulations/avf.py
src/vasp/simulations/offset_stenosis.py
src/vasp/simulations/simulation_common.py

This PR adds a function to compute the minimum of Jacobian, which could be used to measure the quality of the mesh.
This can be used to help investigate the reason for divergence. 
Ref. Fig.6 in this paper: https://www.ljll.fr/~frey/papers/meshing/Wick%20T.,%20Fluid-structure%20interactions%20using%20different%20mesh%20motion%20techniques.pdf

add a function to compute the minimum of Jacobian (displacement)

---

docker/Dockerfile

Fixes an issue where the Docker build fails due to an uninitialized mamba environment. The fix ensures the environment is explicitly created before updating it with `environment.yml`.

Fix mamba environment creation in Dockerfile

---

src/vasp/automatedPostprocessing/postprocessing_h5py/create_hi_pass_viz.py

This pull request modifies the default values for the `--bands` argument in `create_hi_pass_viz.py ` The original default value was too large and could potentially create artifacts. Lowering to 1000Hz should avoid this problem.

lower default filter band range

---

src/vasp/postprocessing/postprocessing_fenics/compute_hemodynamics.py
src/vasp/postprocessing/postprocessing_fenics/compute_stress_strain.py
src/vasp/postprocessing/postprocessing_fenics/create_hdf5.py
src/vasp/postprocessing/postprocessing_fenics/postprocessing_fenics_common.py

@jorgensd  suggested that we run `create_hdf5.py`, which separate fluid velocity and solid displacement, inside `compute_hemodynamics.py` and `compute_stress_strain.py`, so that users do not need to run them separately. This PR addresses that.

update `postprocessing_fenics` to automatically run `create_hdf5`

---

.github/workflows/check_and_test_package.yml
environment.yml

Fixing CI related issues. `sympy` was recently updated to version `1.14` which seemed to cause problem with `FEniCS`. The issue is temporarily solved by pinning the `sympy` version to `1.13.3`

Fix CI issues
